source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rails-api'
gem 'mysql2'

group :development do
  gem 'spring'
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem 'active_model_serializers', '~>0.10.0'
gem 'devise'
gem 'rack-cors'
